version: 2
updates:
  - package-ecosystem: docker
    directory: /handle-errors
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
