version: "3.7"

services:
  authelia:
    container_name: authelia
    depends_on:
      - openldap
      - postgres
      - redis
    env_file:
      - .env
    environment:
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /run/secrets/ldap-admin
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/jwt
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/smtp
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/session
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      TZ: America/New_York
    secrets:
      - jwt
      - ldap-admin
      - postgres-password
      - session
      - smtp
    image: authelia/authelia:4.21
    networks:
      - authelia
      - traefik
    restart: always
    volumes:
      - ./authelia:/config

  docker-socket-proxy:
    environment:
      CONTAINERS: 1
    image: tecnativa/docker-socket-proxy
    networks:
      - docker-socket-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  handle-errors:
    build:
      context: ./handle-errors
    networks:
      - traefik
    restart: always

  openldap:
    container_name: authelia-openldap
    image: osixia/openldap:1.4.0
    environment:
      LDAP_ADMIN_PASSWORD_FILE: /run/secrets/ldap-admin
      LDAP_CONFIG_PASSWORD_FILE: /run/secrets/ldap-config
    secrets:
      - ldap-admin
      - ldap-config
    networks:
      - authelia
    restart: always
    volumes:
      - ldap_db:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  postgres:
    container_name: authelia-postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    secrets:
      - postgres-password
    image: postgres:9.6-alpine
    networks:
      - authelia
    restart: always
    volumes:
      - authelia-postgres-data:/var/lib/postgresql/data

  redis:
    container_name: authelia-redis
    image: redis:6.0-alpine
    restart: always
    networks:
      - authelia

  traefik:
    depends_on:
      - authelia
      - docker-socket-proxy
      - handle-errors
    env_file:
      - .env
    image: traefik:v2.3
    networks:
      - docker-socket-proxy
      - traefik
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./acme:/etc/acme
      - ./dynamic-conf:/etc/traefik/dynamic-conf:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro

  whoami:
    container_name: simple-service
    image: containous/whoami:v1.5.0
    networks:
      - traefik

secrets:
  jwt:
    file: authelia/secrets/jwt
  postgres-password:
    file: authelia/secrets/postgres-password
  session:
    file: authelia/secrets/session
  smtp:
    file: authelia/secrets/smtp
  ldap-admin:
    file: authelia/secrets/ldap-admin
  ldap-config:
    file: authelia/secrets/ldap-config

networks:
  authelia:
  docker-socket-proxy:
  traefik:
    external: true

volumes:
  authelia-postgres-data:
  ldap_config:
  ldap_db:
