accessLog: {}

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/acme/acme.json
      httpChallenge:
        entryPoint: web

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

global:
  checkNewVersion: true
  sendAnonymousUsage: false

providers:
  docker:
    endpoint: tcp://docker-socket-proxy:2375
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic-conf
    watch: true
