accessLog: {}

api:
  dashboard: true

log:
  level: DEBUG # CHANGEME: Use higher log level instead
  # level: INFO

certificatesResolvers:
  letsencrypt:
    acme:
      # CHANGEME: Use a real email (to receive notifications from Let's Encrypt)
      email: changeme@foobar.com
      # CHANGEME: This is a staging server. Update to the prod server
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /etc/acme/acme.json
      httpChallenge:
        entryPoint: web
      # CHANGEME: If you'd like to use the DNS challenge for a wildcard cert.
      # See https://doc.traefik.io/traefik/https/acme/#dnschallenge
      # dnsChallenge:
      #   provider: TODO

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: tcp://docker-socket-proxy:2375
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic-conf
    watch: true
