# See https://www.authelia.com/configuration/prologue/introduction/ for options
server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: auth.docker.localhost # CHANGEME: Set as AUTH_SERVER_HOST
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      iterations: 3
      key_length: 32
      salt_length: 16
      parallelism: 4
      memory: 64

# Read https://www.authelia.com/configuration/security/access-control/ carefully
# It is easy to misconfigure these.
access_control:
  default_policy: deny
  rules:
    # CHANGEME: Configure for your hosts.
    # The auth domain should always be set to bypass.
    - domain: auth.docker.localhost
      policy: bypass
    - domain: whoami.docker.localhost
      policy: bypass
    - domain: traefik.docker.localhost
      policy: one_factor
    - domain: secure.docker.localhost
      policy: two_factor
      subject:
        - group:admin

session:
  name: authelia_session
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: docker.localhost # CHANGEME: domain associated with the login subdomain

  redis:
    host: authelia-redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  postgres:
    host: authelia-postgres
    port: 5432
    database: authelia
    username: authelia

notifier:
  disable_startup_check: true
  filesystem:
    # CHANGEME: Use the SMTP configuration (see CHANGEME in docker-compose.yml)
    filename: /config/notification.txt
  # smtp:
  #   username: changeme@gmail.com
  #   sender: no-reply@auth.docker.localhost
  #   host: smtp.gmail.com
  #   port: 587

theme: auto
