# See https://www.authelia.com/docs/configuration/ for options
host: 0.0.0.0
port: 9091
log_level: debug

totp:
  issuer: auth.docker.localhost # CHANGEME: Set as AUTHELIA_HOST
  period: 30
  skew: 1

authentication_backend:
  ldap:
    additional_groups_dn: ou=groups
    additional_users_dn: ou=users
    base_dn: dc=example,dc=org
    display_name_attribute: displayname
    group_name_attribute: cn
    groups_filter: (&(member={dn})(objectclass=groupOfNames))
    mail_attribute: mail
    url: ldap://authelia-openldap
    user: cn=admin,dc=example,dc=org
    username_attribute: uid
    users_filter: (&({username_attribute}={input})(objectClass=person))

access_control:
  default_policy: deny
  rules:
    # CHANGEME: Configure for your hosts.
    # The auth domain should always be set to bypass.
    - domain: auth.docker.localhost
      policy: bypass
    - domain: "*.docker.localhost"
      policy: two_factor

session:
  name: authelia_session
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: docker.localhost # CHANGEME: domain associated with the login subdomain

  redis:
    host: authelia-redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  postgres:
    host: authelia-postgres
    port: 5432
    database: authelia
    username: authelia

notifier:
  filesystem:
    filename: /config/notification.txt # CHANGEME: Use the SMTP configuration
  # smtp:
  #   username: changeme@gmail.com
  #   sender: no-reply@auth.docker.localhost
  #   host: smtp.gmail.com
  #   port: 587
