http:
  middlewares:
    secured:
      chain:
        middlewares:
          - auth@docker
          - redirect-to-https
          - error-pages

    redirect-to-https:
      redirectScheme:
        scheme: https

    error-pages:
      errors:
        status:
          - "400-499"
          - "500-599"
        service: handle-errors-traefik-proxy@docker
        query: "/{status}"

  routers:
    http-catchall:
      entrypoints:
        - web
      middlewares:
        - redirect-to-https
        - error-pages
      rule: hostregexp(`{host:.+}`)
      service: noop

  services:
    noop:
      loadBalancer:
        servers:
          - url: http://192.168.0.1
