x-default-router: &default-router
  middlewares:
    - secured
  tls:
    certResolver: letsencrypt

http:
  middlewares:
    secured:
      chain:
        middlewares:
          - auth@docker
          - redirect-to-https
          - error-pages

    redirect-to-https:
      redirectScheme:
        scheme: https

    error-pages:
      errors:
        status:
          - 400-499
          - 500-599
        service: handle-errors-traefik-proxy@docker
        query: /{status}

  routers:
    http-catchall:
      entrypoints:
        - web
      middlewares:
        - redirect-to-https
        - error-pages
      priority: 9999
      rule: HostRegexp(`{host:.+}`)
      service: noop

    # Example of a router
    my-router:
      <<: *default-router
      rule: Host(`mysubdomain.docker.local`)
      service: my-service

  services:
    noop:
      loadBalancer:
        servers:
          - url: http://192.168.0.1

    # Example of a service
    my-service:
      loadBalancer:
        servers:
          - url: http://192.168.1.23:8123
