name: Linting
on: pull_request

jobs:
  yaml-lint:
    name: Run yaml linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Configure Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install yamllint
        run: pip install yamllint==1.34.0
      - name: Run yamllint
        run: yamllint .
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          check_together: "yes"
        env:
          SHELLCHECK_OPTS: -e SC2034 --shell=bash
  shfmt:
    name: Shell format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
      - name: Check formatting
        run: shfmt -s -d .
