name: Linting
on: pull_request

jobs:
  yaml-lint:
    name: Run yaml linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install yamllint
        run: pip install yamllint==1.24.2
      - name: Run yamllint
        run: yamllint .
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@e5c9260d1115f89914b306831f831def43d2dc2d
        with:
          check_together: "yes"
        env:
          SHELLCHECK_OPTS: -e SC2034 --shell=bash
  shfmt:
    name: Shell format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
      - name: Check formatting
        run: shfmt -s -d .
