name: Linting
on: pull_request

jobs:
  yaml-lint:
    name: Run yaml linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install yamllint
        run: pip install yamllint==1.24.2
      - name: Run yamllint
        run: yamllint .
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@203a3fd018dfe73f8ae7e3aa8da2c149a5f41c33
        with:
          check_together: "yes"
        env:
          SHELLCHECK_OPTS: -e SC2034 --shell=bash
  shfmt:
    name: Shell format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Install shfmt
        run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
      - name: Check formatting
        run: shfmt -s -d .
